name: rnb-backend
volumes:
  postgres_data:
networks:
  rnb-internal:
    name: rnb-internal
services:
  postgres:
    container_name: rnb-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rnb-internal